steps:
  # build & push the container image
- name: "build & push the container image"
  args: ["--cache=true", "--cache-ttl=48h", "--destination=gcr.io/message-frame/todo:latest"]
  # Deploy container image to Cloud Run
- name: "Deploy container image to Cloud Run"
  args: ['beta', 'run', 'deploy', 'todo', '--image', 'gcr.io/message-frame/todo:latest', '--region', 'us-central1', '--allow-unauthenticated', '--platform', 'managed']